# Generated by Django 2.2.4 on 2019-09-05 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('T', 'Teacher'), ('S', 'Student')], default=1, max_length=30)),
                ('avatar', models.ImageField(default='pic_folder/noimg.jpg', upload_to='pic_folder/')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('department', models.CharField(choices=[('FY', 'First Year'), ('CS', 'Computer Engineering'), ('IT', 'Information Technology'), ('ET', 'Electronics and Telecommunication'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('unit', models.IntegerField()),
                ('file', models.FileField(upload_to='notes_folder/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='napp.Author')),
            ],
            options={
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('sentiment', models.CharField(choices=[('pos', 'Positive'), ('neg', 'Negative'), ('neu', 'Neutral')], max_length=20)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_by', to='napp.Author')),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='napp.Notes')),
            ],
        ),
    ]
