# Generated by Django 2.2.4 on 2019-09-14 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('napp', '0002_auto_20190914_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
